### ISSUE TITLE
Install pinned with a single action for python

### ISSUE THREAD

**Issue by kriswuollett** [install-pinned/.github#1]
I discovered this collection of actions/repos when trying to search for installing release binaries from GitHub Releases. The install-pinned actions all seem to differ mostly just on the in the requirements file, i.e.,  [`requirements.txt`](https://github.com/install-pinned/pdm/blob/ae8ff57d09fc3a598e02cfcc135e430d8155914d/requirements.txt).

From a GitHub user this felt like spamming the actions catalog -- there are currently 25 different actions for `install-pinned` that take up room on the search results:

![CleanShot 2024-12-23 at 12 18 32@2x](https://github.com/user-attachments/assets/35ed54b3-deb4-44bf-9a06-38ccf8052d4c)

But don't get me wrong, I do think this concept is very useful. Perhaps consider making this a single action just for "python" in a single repo that contains a structure like `{tool}/{version}/requirements.txt`? The size of a monorepo might be okay compared to overhead and latency of using submodules?

So instead of multiple invocations of actions like:

```yaml
- name: Install black from PyPI
    uses: install-pinned/black@670a06c448b0a66ed592d03f590f0f652d61fb04  # 24.10.0
- name: Install ruff from PyPI
    uses: install-pinned/ruff@723ac3f92a8930bf8d7fef4cfbf40f02abd84c3a  # 0.8.4

# and so on...
```

Users may be able to do something like the following and install multiple tools in one step:

```yaml
- name: Install Python tools
  uses: install-pinned/python@ce13d531c9352c7071a9f10f1310b8aad601685f  # catalog as of 2024-12-23
  with:
    black: "24.10.0"
    ruff: "0.8.4"
```

If the concept works,  I think you may be able to expand to other languages as well. It could also reduce the need for each tool maker to make their own independent installer action.

However from a security perspective, I think any lockfile generation needs to be open source as well so that a third-party can verify the lockfiles checked into the your repo are easily reproducible from a single command.
